# Generated by Django 3.1.7 on 2021-07-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_referuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referuser',
            name='referId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='referuser',
            name='refferedBy',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
