# Generated by Django 3.0.5 on 2021-03-22 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptToEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.FileField(upload_to='script_Editor/userScripts')),
                ('dateCreated', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Scripts',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('FormId', models.AutoField(primary_key=True, serialize=False)),
                ('RateValue', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('RateNarration', models.CharField(default='', max_length=20)),
                ('RateConversion', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='editor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ScriptName', models.CharField(blank=True, max_length=50, null=True)),
                ('bodyTxt', tinymce.models.HTMLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
