# Generated by Django 3.1.7 on 2021-04-03 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Meditor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionEditor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ScriptName', models.CharField(blank=True, max_length=50, null=True)),
                ('bodyTxt', tinymce.models.HTMLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
